### ISSUE TITLE
hc0_linux.h: HC_FPS macro is not used

### ISSUE THREAD

**Issue by aolo2** [baines/halcyon#1]
The single-file version of the library does not use the defined HC_FPS value. Instead, 60UL is hardcoded (see hc0_linux.h:234). Changing the define to 60UL from 60 and using it seems to have fixed the issue for me.

**Comment by baines** [comment]
Thanks for the report.

Originally `HC_FPS` was only used in the audio code - which was removed from `hc0_linux.h` - but the #define was left around by accident.

I've updated the code to use `HC_FPS` in the timing logic now, and changed it to have the UL suffix.

I think due to the way the XPresent extension is being used, the video refresh rate will be VSYNC'd, so not necessarily always 60 fps - but I don't have a >60hz monitor to test with and see what happens.

**Comment by baines** [comment]
Closing since the define is used now.
